baseURL = "https://ryoheishome.github.io/symmetry/"
title = "Ryohei Kobayashi"
theme = "PaperMod"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "EN"
    languageCode = "en"
    contentDir = "content/en"
    weight = 1
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "CV"
        url = "en/cv/"
        weight = 10
      [[languages.en.menu.main]]
        name = "Publications"
        url = "en/publications/"
        weight = 20
      [[languages.en.menu.main]]
        name = "Research"
        url = "en/research/"
        weight = 30
      [[languages.en.menu.main]]
        name = "Talks"
        url = "en/talks/"
        weight = 40

  [languages.ja]
    languageName = "日本語"
    languageCode = "ja"
    contentDir = "content/ja"
    weight = 2
    title = "小林 良平"
    [languages.ja.menu]
      [[languages.ja.menu.main]]
        name = "経歴"
        url = "ja/cv/"
        weight = 10
      [[languages.ja.menu.main]]
        name = "業績"
        url = "ja/publications/"
        weight = 20
      [[languages.ja.menu.main]]
        name = "研究"
        url = "ja/research/"
        weight = 30
      [[languages.ja.menu.main]]
        name = "講演の記録"
        url = "ja/talks/"
        weight = 40
